### ISSUE TITLE
Clear code coverage decoration does not clear history spot

### ISSUE THREAD

**Issue by kborowinski** [maziac/DeZog#10]
**Describe the bug**

Clear code coverage decoration does not clear history spot.

**To Reproduce**

![dezog_decoration](https://user-images.githubusercontent.com/16168755/75430162-3a138b00-594b-11ea-804b-d8b760efd6f7.gif)

**Version etc. (please complete the following information):**
 - DeZog 0.11.0
 - ZEsarUX SW Version: 8.1

**Comment by maziac** [comment]
Yes,  "dezog: Clear current code coverage decoration" does clear only the code coverage.

The history spot uses the instruction history and not the code coverage. These are independent implementations.

Is this maybe documented wrongly? If so, please point me to the docs.

(at the moment) you cannot clear the instruction history. You can only disable it in the launch.json before you start a debug session.

Do you feel the need for such a command to clear the instruction history?

**Comment by kborowinski** [comment]
It would be useful to have command that clears decoration and history in one go so you don't have to issue two commands from the menu or if you are not willing to do that, then just add another command to clear history please.

BTW How to configure DeZog 0.12.0 (alpha) to work with ZEsarUX remote protocl. Could you have quick look at the #9

**Comment by maziac** [comment]
Would you like a command for enabling/disabling all the decorations or would you like a command to clear the instruction history (as with clearing the coverage).
This is a little bit different.
What is your intention here/for what purpose do you need the command?

"BTW How to configure DeZog 0.12.0 (alpha) to work with ZEsarUX remote protocl. Could you have quick look at the #9"
Actually there is nothing special about 0.12.0. I use it with no problems on macOS and I also verified that it is working on Windows.
Maybe something has gone wrong with the vsix files.
I will issue an update soon, maybe you could try that once again.

**Comment by kborowinski** [comment]
I would like both:
1. Option for enabling/disabling all the decorations, like you can do with history spot, ie:
```
"history": {
    "spotCount": 0
}
```
2. Command to clear instruction history. After debugging session I don't want the instructions history to be shown in the source. Right now I am reloading window (i.e. *Developer: Reload Window*) to clear the instructions history

Ps. OK, I'll try again after you update the vsix.

BTW Thanks for that amazing plugin, I use it on daily basis and love it!

**Comment by maziac** [comment]
I currently think of the following:
- Remove all decorations when the debug session ends
- with the exception when running unit tests: coverage decoration should remain after the unit test
- a command to clear all decorations (but they would re-appear on the next step)
- maybe a command to clear the instruction history. But I‘m not really sure if this is still needed with the other implementation above.

Could you please check if this would be OK for you.

**Comment by kborowinski** [comment]
That seems reasonable.

**Comment by maziac** [comment]
Here is the new release with the changes:
https://github.com/maziac/DeZog/releases/tag/v0.13.0

**Comment by kborowinski** [comment]
I just did quick test with **DeZog 0.13.0** and it looks like there is no decorations at all during debug session:

![dezog_no_decorations](https://user-images.githubusercontent.com/16168755/76449050-acfd1700-63cb-11ea-9f12-8c63068e457b.gif)

**Comment by maziac** [comment]
Please try with zesarux.
The internal simulator has no coverage yet. Please wait for the next release :-)

**Comment by kborowinski** [comment]
I would love to test it with zesarux but zesaurx is giving me panic every single time I try to debug:

![dezog_panic](https://user-images.githubusercontent.com/16168755/76456687-a7a5c980-63d7-11ea-8020-74b389dc7c0a.gif)

**Comment by maziac** [comment]
I see :-(

I pinged Cesar once again about this. Let's see.

Meanwhile here is the 0.13.1 with coverage available for the internal simulator.
https://github.com/maziac/DeZog/releases/tag/v0.13.1

(Only coverage, no history yet)

**Comment by kborowinski** [comment]
Thanks for pinging Cesar, it gets really frustrating to debug with Zesarux on Windows lately. And code coverage works great on 0.13.2 (I work on daily builds of DeZog ;)

**Comment by maziac** [comment]
I close this one. There is another 'issue' for the zesarux crash problem.
