### ISSUE TITLE
Incompatibly: ZEsarUX 10.2: Breakpoints not working

### ISSUE THREAD

**Issue by maziac** [maziac/DeZog#101]
**There are some incompatibility problems between DeZog and ZEsarUX at the moment with ZEsarUX v10.2.**

**The workaround for the moment, for both: DeZog 2.7.x and DeZog 3.0, is to use ZEsarUX 10.1.**
You find it here: https://github.com/chernandezba/zesarux/releases/tag/ZEsarUX-10.1

ZEsarUX will get a compatibility fix with the next, the 10.3, release.
At that time I will also release a new version of DeZog to become compatible again.

**Comment by maziac** [comment]
Some more info:
With DeZog 2.7.x the breakpoints work up to (<=) 10.1 ZEsarUX.
For DeZog 3.0.0 there exists a solution to get the breakpoints working, but then there still is a problem in ZEsarUX that a menu window pops up after connection close when a breakpoint has been hit.
This window hinders the next debug session setup.

To simplify things I will not release a half working solution for 10.2 but wait until the 10.3 is released (note: the problem has already been solved in ZEsarUX with commit 1257e3c, it's just not yet released.)

In DeZog 3.0.0 I would have to change the function sendSetBreakpoint.
The code exists already, but is commented.

**Comment by maziac** [comment]
Note to myself: when fixing this also correct the documentation about compatible zesarux version.

**Comment by michal-cab** [comment]
hello, i am searching for dev/toolchain for zx spectrum asm. combo of vscode, sjasmplus, dezog and zesarux seems like best option for me now (concerning debugging, workflow etc.). But unfortunately i have to confirm incompatibility of DeZog 3.2.4 and ZEsarUX v.X (10th Anniversary edition. 16 May 2023) . ZRCP seems to work and dezog can somehow communicate with zesarux - i can step through asm line by line and observe content of registers and stack, but when i manually create breakpoints in vscode and  run compiled code - they are just ignored... :-(

hope it is not big issue and can be fixed - i would appreciate it quite much :). ev. thnx for any info about progress.

and thnx for great work/debugger anyway (still works well with internal zx emulator - if you dont need precise timing)

**Comment by maziac** [comment]
Good timing.
Yes, ZEsarUX 10.2 (and 10.3) were not supported in DeZog <= 3.2.4.
You had to use 10.1. There was an incompatibility in the zrcp.
I waited for the 10.3 to become official to release the DeZog 3.3. 3.3 does support ZEsarUX 10.3.
It has just been released. Please install from the marketplace and check if it fixes your problem.

**Comment by michal-cab** [comment]
confirming that stopping on breakpoints is working with dezog 3.3 + zesarux 10.3 - great and thnx for info!

**Comment by maziac** [comment]
Thanks for the feedback
