### ISSUE TITLE
DeZog - Code/Data Reference Count Missing

### ISSUE THREAD

**Issue by robgmoran** [maziac/DeZog#103]
Bug:
After installing DeZog v3.1.0 in Visual Studio Code 1.74.0, the reference count that proceeds Z80 code routines and data variables appears to have disappeared.

1. Load Z80 code in Visual Studio Code
Reference count does not appear

Expected behavior
A reference count label previously appeared before all routines and data variables, which could then be clicked to reveal the instances where this was referenced throughout the code.

Components:
 - DeZog SW Version: 3.1.0
 - OS: Windows 10
 - Remote: Visual Studio Code 1.74.0 & CSpect

[launch.json.txt](https://github.com/maziac/DeZog/files/10188163/launch.json.txt)

**Comment by maziac** [comment]
I guess you are referring to asm-code-lens, not DeZog.

Both extensions were suffering from an incompatibily with vscode 1.74.
DeZog 3.1.0 and asm-code-lens 2.1.0 should be compatible with 1.74.

Most probably you just need to update asm-code-lens.

**Comment by maziac** [comment]
Was probably an incompatibility with z80 micro assembler and as-Moll code lens.
