### ISSUE TITLE
DeZog not found in marketplace

### ISSUE THREAD

**Issue by Duefectu** [maziac/DeZog#11]
**Describe the bug**
When I type "DeZog" on VSCode 1.43.0: "No extensions found"

**To Reproduce**
1. Go to 'Extension"
2. Type on seach box DeZog
3. Result: "No extensions found"

**Expected behavior**
The extension DeZog to install

**Screenshots**
![image](https://user-images.githubusercontent.com/5257547/76576797-802c2b00-64c3-11ea-9eac-b512a5de89dd.png)

**Version etc. (please complete the following information):**
 - SW Version: VS Code v1.43.0
 - OS: Windows 10
 - ZEsarUX SW Version: 8.1

**Additional context**
none

**Comment by kborowinski** [comment]
As a workaround you can download the latest version from [here](https://github.com/maziac/DeZog/releases) (it's in the assets).

**Comment by maziac** [comment]
I'm not sure when I will release the next time to the marketplace, could be soon or later.
So best is to update from the link above.

**Comment by Duefectu** [comment]
The correct name to search is "maziac" or "Z80 debugger",
Maybe updating the install instructions:
"In Visual Studio Code simply install "DeZog" (maziac.dezog) from the Marketplace."

**Comment by maziac** [comment]
DeZog v1.1.0 is now available in the market place.

**Comment by niel** [comment]
I am unable to install from the market place too. None of the instruction for doing so in VS Code even show it as being available. I'm using Manjaro Linux and have tried both the AUR version and building Code myself. Is there some dependency that might be missing?

**Comment by maziac** [comment]
Just checked  (on mac):
![Bildschirmfoto 2021-05-12 um 17 35 36](https://user-images.githubusercontent.com/3081973/118003009-7791e780-b348-11eb-93aa-3fe534638539.jpg)
I.e. the extension should be there.

Are you able to see any other extension. Maybe the marketplace is not working at all in your installation.

**Comment by niel** [comment]
When I build the dev version, nothing there. The AUR version (Code - OSS 1.55.2-1) definitely has extensions available, just not Dezog. I can see it fine if I visit the marketplace website.

**Comment by maziac** [comment]
I now also tried Ubuntu (16.04), vscode 1.46.1.
No problem.
Maybe you can simply try to install from here: 
https://github.com/maziac/DeZog/releases/tag/v2.2.4

**Comment by niel** [comment]
I would just like to get the issue identified so I can fix it, as it prevents me even finding extensions through VS Code. I have found a workaround: Use the Marketplace to find an extension, and on the details page download the vsix file and manually install. It's a PITA as it , doesn't allow for updating the extension automatically.

**Comment by maziac** [comment]
Is there maybe a vpn used or a firewall preventing access?
I think vscode is using more than just the download link itself.

**Comment by niel** [comment]
No VPN/Firewall on this computer. My router has a firewall, but should be allowing all out-going requests. Any ports/protocols I should make sure are open?

**Comment by maziac** [comment]
I don't think I can help you with this.
Have you considered to contact Microsoft directly?

**Comment by niel** [comment]
Thanks for taking the time to try helping.
I am looking at the VS Code for an appropriate means of asking for help. Their issues seems to be for bugs only, not more general support questions.

**Comment by niel** [comment]
Turns out the Manjaro build does not use the MS Marketplace. Instead it uses https://open-vsx.org/ hence no responces to a query. :-(
Would you consider putting the extension on that market place too?

**Comment by maziac** [comment]
Actually I'm reluctant to do so.
I would like to keep the administrative effort as low as possible for myself.
You can always install the extension from the vsix file If you need an alternative.
