### ISSUE TITLE
Improvements for editing the memory contents in Memory View

### ISSUE THREAD

**Issue by vampirehunt2** [maziac/DeZog#111]
I would like to:

- be able to directly type ASCII characters in the right side of the MemoryView (currently that part is read-only)
![image](https://user-images.githubusercontent.com/70143882/226200058-a888ad48-2774-4772-a888-cb0a2f36912b.png)

- be able to default to hex when changing the memory contents in the left side of MemoryView (currently I have to type 'h' after each two hex digits)
- have the currently edited memory cell automatically advance to the next address after editing the previous address, without having to click into each memory location that I want to edit. This would allow to easily modify multiple consecutive memory location.

I could *potentially* contribute these changes.

**Comment by maziac** [comment]
If you want you can create a PR for this.
But I could imagine it gets rather complicated.

If that would help, I could also extend the "-msetb" command to support a string and e.g. a series of bytes.

For the hex input (wo 'h') I'm not so sure: currently you have to use the extension everywhere else as well. Would be inconsistent here to have a hex input. And how should the decimal input work?

**Comment by vampirehunt2** [comment]
_how should the decimal input work?_
I would say if no base is specified AND hex digits are entered, default to hex. That would be my preferred method, however, since other people's requirements may vary, I was actually thinking of a user preference where you could set your default base for the Memory View.

**Comment by maziac** [comment]
So one would have to enter "10" for 10 or 0xA but if someone enters "F0" it would be 240 or 0xF0?
Seems inconsistent to me.

**Comment by maziac** [comment]
Decided not to implement.
