### ISSUE TITLE
Labels error in launch.json: "Cannot evaluate 'topOfStack':"

### ISSUE THREAD

**Issue by ElasticCoder** [maziac/DeZog#122]
**Describe the bug**
VSCode debugging displays the error Cannot evaluate 'topOfStack' (stack_top).

**To Reproduce**
The attached launch.json (and game.zip which contains a very basic game) will not start debugging. 
The topOfStack property in launch.json does not work with a label. You have to put a value in (e.g. "topOfStack": "0xFFF0").

produce the behavior:
1. Start Debugging

**Expected behavior**
The address defined for the label is used for the top of stack memory location.

**Version etc. (please complete the following information):**
 - DeZog SW Version: 3.3.2
 - OS: Windows 11
 - Remote: zrcp (ZEsarUX)

**Additional context**
[launch.json](https://github.com/maziac/DeZog/files/13847073/launch.json)
[game.zip](https://github.com/maziac/DeZog/files/13847078/game.zip)

**Comment by maziac** [comment]
Not sure if you zipped the complete project. Probably not, as your zip file is missing the list or sld file.
With Assembler sources alone dezog cannot associate labels with address values.
Therefore it requires an assembler. 
Furthermore the launch.json has wrong entries (maybe some old entries).
You can find this from the squiggled lines:
![Bildschirmfoto 2024-01-07 um 14 32 31](https://github.com/maziac/DeZog/assets/3081973/ac71cd01-f914-42ca-adf2-ce799f2e5013)

In https://github.com/maziac/z80-sample-program you find a sample program that does use a label for "topOfStack".

If you still have problems please attach here the complete project also with list or sld file and the command line or makefile how it is created.

**Comment by ElasticCoder** [comment]
Thank you for your reply - you have steered me to the solution. 

I had based my Z80 source on other examples elsewhere on the Internet, but the problem was I was not emitting an SLD file. Producing a SLD file makes it work.

The changes I made were:
```tasks.json``` adding the --sld directive. This makes sjasmplus emit an SLD file.

```
    "tasks": [
        {
            "label": "sjasmplus",
            "type": "shell",
            "command": "sjasmplus",
            "args": [
                "--lst=${fileDirname}/${fileBasenameNoExtension}.lst",
                "--sld=${fileDirname}/${fileBasenameNoExtension}.sld",
                "${file}"
            ],
...
```
```launch.json``` adding the sjasmplus block, which allows dezog to load in the tracing data.
```
"sjasmplus": [
                {
                    "path": "${fileDirname}/${fileBasenameNoExtension}.sld"
                }
            ],
```

And again, thank you for the tool. I am enjoying using it.
