### ISSUE TITLE
Unable to connect to internal or zesarux emulator

### ISSUE THREAD

**Issue by timlinux** [maziac/DeZog#123]
Firstly, thank you for this wonderful project! A ZX Spectrum was my first computer and I am really enjoying relearning assembler for it!

I have followed in detail the various instructions for setting up my DeZog work. Just a little overview of my setup:

* OS: Linux (Nixos)
* VSCode: 1.773
* Zesarux: ZEsarUX v.10.0 - Clive Sinclair edition. 4 October 2021
* Assembler: SjASMPlus Z80 Cross-Assembler v1.18.3 
* DeZog: v3.3.2
* Emulating: ZXSpectrum 48k

## Current status

- [ ] Compiling - works
- [ ] Launching ZESaruX from the terminal menu works - works
- [ ] Verifying that the debugger has exposed a connection on port  10000 via telnet - works
- [ ] Launching the compiled application on the ZESaruX virtual appliance - fails

I have tested with both your z80-sample-program project and with my scratch area with a minimal compilable programme in it (https://github.com/timlinux/z80).

I appreciate that I am not giving you much actual diagnostic information and that is really my question - how can I debug / view logs etc. to see why the launch (and debugging fails)?

Here is a short clip of what happens when it fails:

[Screencast from 2024-01-11 23-11-43.webm](https://github.com/maziac/DeZog/assets/178003/26b10bb6-6b9a-488f-bdd7-612aae4d680e)

**Comment by maziac** [comment]
A few basic questions first:
- The z80-sample-program is also not working for you, correct?
- Did you succeed starting the program in the internal simulator? Could you 'step' in there?

From what I can see from the video there seems to be a connection between dezog and zesarux as the (smart) loading starts.

I have also tested on my Mac with your setup (your tasks.json) and debugging works fine for me.
Do you start zesarux from your tasks.json or do you start it manually with other command line arguments?

For the diagnostics:
In the "OUTPUT" tab select the "DeZog Transport".
It logs the whole communication between dezog and zesarux.
If something goes wrong or stucks, most likely it can be seen here.
Please clear the window, start a new debug session and then attach the log here.
There is also another log "DeZog", please attach the log (from the same session) as well.

**Comment by timlinux** [comment]
Hi

Thank you for taking the time to reply to my issue. Answers in line below:

> A few basic questions first:
> 
>     * The z80-sample-program is also not working for you, correct?
>     * Did you succeed starting the program in the internal simulator? Could you 'step' in there?


Neither approach works for me - I have made a light fork of your z80-sample-program which uses direnv and nix shell to repeatably create a from-clean setup environment. Assuming no changes are needed to your sample program after checking it out, for me it also does not run.

[Screencast from 2024-01-14 18-45-04.webm](https://github.com/maziac/DeZog/assets/178003/259f22cd-ce1f-4cee-bc95-20c423b9655e)

Unfortunately I could not test with CSpect since it it not packaged for NixOS.
I do have fuse-emulator installed but it seems that is not supported by DeZog.



> 
> 
> From what I can see from the video there seems to be a connection between dezog and zesarux as the (smart) loading starts.
> 
> I have also tested on my Mac with your setup (your tasks.json) and debugging works fine for me. Do you start zesarux from your tasks.json or do you start it manually with other command line arguments?

I have tried it both using the task and manually from the command line. The above screencast shows me testing using the task. Note I made two small tweaks to the task in [my fork](https://github.com/timlinux/z80-sample-program) in order to allow it to launch:

![image](https://github.com/maziac/DeZog/assets/178003/e1a443ae-0dcf-4a65-b7a9-90e26e675e40)



> 
> For the diagnostics: In the "OUTPUT" tab select the "DeZog Transport". It logs the whole communication between dezog and zesarux. If something goes wrong or stucks, most likely it can be seen here. Please clear the window, start a new debug session and then attach the log here. There is also another log "DeZog", please attach the log (from the same session) as well.

Hmm yeah that is where I went to look for logs first when I got issues, but for me, I don't have any DeZog option.

[Screencast from 2024-01-14 18-56-23.webm](https://github.com/maziac/DeZog/assets/178003/066b8d09-66ad-4aac-b03b-33c96bca4491)

Maybe there is something peculiar with my environment. I will test on a Mac I have here and see if I also get the same problem there. I'll update this issue after.

Thanks!

**Comment by maziac** [comment]
There is something wrong with your dezog installation as far as I can see.
If dezog is installed right you should be able to use the internal simulator.
It does not have any dependency to some other component.
Additionally the OUTPUT logs are not appearing.

Have you tried to install the extension (the six) from within vscode?
The vsix files can be found under dezog-github releases.

**Comment by timlinux** [comment]
@maziac thanks for your feedback above. So I went and did some testing:

- [ ] Tested on my macOS machine - built in emulator works perfectly, out of the box
- [ ] Tested with newer / older versions of vscode without change in outcome
- [ ] Tested by directly installing from VSIX in Nixos without success

I guess there is something going on  with the way VSCode is packaged on nixos, or the way that DeZog works which isn't compatible with the NixOS filesystem layout etc.

**Comment by timlinux** [comment]
I am going to close this for now as I don't have enough knowledge of VSCode to figure out why Dezog does not install properly. For now I found a work around to use Lima to set up an Ubuntu container and run vscode in my browser - as described in my notes here : https://github.com/timlinux/z80?tab=readme-ov-file#running-under-lima

**Comment by timlinux** [comment]
Thank you for trying to help by the way @maziac

**Comment by timlinux** [comment]
@maziac  Just a little update on this - DeZog now works for me on NixOS 24.11 and VSCode 1.96.4 - no idea what actually fixed it, but pleased to have it working now!
