### ISSUE TITLE
Internal debugger for ZX81 developments

### ISSUE THREAD

**Issue by stevexyz** [maziac/DeZog#128]
Recently I was trying to come back to some ZX81 development, but discovered that for some reason current version of Zesarux is not working with DeZog.
Unfortunately for ZX81 seems there are no other compatibilities, and I was wondering if it would be possible to extend the internal debugger to support also this machine.
I think it would also greatly simplify the setup of the development environment needing just VSCode and Dezog, and even without init files if you find a ".p" file with the same name as ".asm" everything could be setup automatically (looking also for sld etc).

**Comment by andrivet** [comment]
There is a fork with what you need. This is explained in the Readme of DeZog: https://github.com/maziac/DeZog#fork
(i am the author of the fork)

**Comment by maziac** [comment]
Yes, please try the fork and see if it fits your needs.
I was also thinking of adding zx81 in the future, but with that fork I think there is little need for it...

**Comment by andrivet** [comment]
I was also thinking of making my fork more compatible with DeZog but I am not sure it is worth the effort. So many ideas, so many projects and not enough time.

**Comment by stevexyz** [comment]
WOW, this is the way!!
The main limitation I see is related to the assembler, unfortunately way too simple for anything more than very basic programs, and surely very much underpowered for my needs (e.g. I’m trying to create a new version of the 1K Real Chess for ZX81). Without reimplementing things (standard undocumented instructions, powerful directives, etc), would it be possible to integrate a more powerful ready one as for example sjasmplus (https://github.com/z00m128/sjasmplus) or fasm/fasmg (https://github.com/jacobly0/fasmg-z80)?

**Comment by andrivet** [comment]
I have backported my code for the ZX81 into the latest version of DeZog and submitted a PR. It does not use my own Z80 assembler but an external one so this should solve your problems. I do not know when Maziac will have the time to review the PR so in the meantime, you can use my (second) fork: https://github.com/andrivet/DeZog/tree/zx81. I have published a VSIX under [Releases](https://github.com/andrivet/DeZog/releases).

**Comment by maziac** [comment]
Hi, thanks very much for the back port. I very much appreciate your work.
As I already mentioned it will probably take some time until I can re-use your work.
Here is my current plan for a "roadmap" just to give you an idea:
1. dezog 3.4.0 (zxndma): in 1 week
2. some other project: Time = ?
3. dezog 3.5.0: zsimremote re-factored as web view: 2 months
4. dezog 3.6.0: zx81 integration

My thoughts so far:
The zsim is a z80 simulator. I.e. the ZX Spectrum additions are _just_ additional HW simulations that can be enabled one by one. If you put the right "HW" together you get the ZX Spectrum (i.e. ula + keyboard + zxbeeper mainly).
I would like to keep it the same for the zx81. I.e. rather than having a separate "zx81sim" I will try to set this inside the current "zsim".
Maybe I'll add something like a "collection" (inside "zsim") where you can just type "zx81" or "zxspectrum" and it enables the defaults with the right HW for you.

**Comment by maziac** [comment]
I changed my plans/schedule and directly started with the zx81 development for dezog.
Please check this release candidate
[dezog-3.5.0-rc1.vsix.zip](https://github.com/user-attachments/files/16677910/dezog-3.5.0-rc1.vsix.zip)
The internal simulator (zsim) has been improved by zx81 features.
Changes are:
  - Simulation of ZX81.
  - Removed "vsyncInterrupt". A VSYNC interrupt is now generated if the Spectrum ULA is enabled.
  - "ulaScreen":
    - Type changed from boolean to 'spectrum' | 'zx81'.
  - Z80 CPU simulation fix: HALT instruction: r is now incremented on each instruction.
  - New debug command, "-ml address filepath", to load binary data into the memory.
  - Fixed setting of A' from the UI.
  - The "zxKeyboard"
    - now supports reading several rows at the same time.
    - type changed to string. "zx81" and "spectrum" style keyboard supported.
    - keyboard visualization improved.
  - The "kempstonJoy" now decodes only the lower 8 bits of the address.
  - A new "costumJoy" type: You can assign the bits and ports yourself.
  - Added "preset" to easily configure a spectrum or zx81 device.

![Bildschirmfoto 2024-08-20 um 17 22 26](https://github.com/user-attachments/assets/823efeaa-6314-41c7-9234-95a6920d55d2)

**Comment by maziac** [comment]
Here is the updated documentation: 
https://github.com/maziac/DeZog/blob/zx81/documentation/Usage.md
https://github.com/maziac/DeZog/blob/zx81/documentation/Migration.md

For a zx81 project you could use the following launch.json:
~~~
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "dezog",
			"request": "launch",
			"name": "zsim - ZX81-16K",
			"remoteType": "zsim",
			"zsim": {
				"preset": "zx81"
			},
			"commandsAfterLaunch": [],
			"history": {
				"reverseDebugInstructionCount": 1000000,
				"spotCount": 10,
				"codeCoverageEnabled": true
			},
			"startAutomatically": false,
			"rootFolder": "${workspaceFolder}",
			"load": "Mazogs.p81",
		}
         ]
}
~~~

**Comment by andrivet** [comment]
Very nice work. A few remarks:
- The frequency for the ZX81 is wrong, it should be 3.25 MHz, not 3.5.
- The image of the keyboard is blurry (low resolution). I have recreated the keyboard in a vector format. I put a version below in SVG. I can try to do the same for the ZX Spectrum if you find this useful.

![ZX81_keyboard](https://github.com/user-attachments/assets/91b08161-8a90-4f62-891a-ebf40059706d)

**Comment by maziac** [comment]
"The frequency for the ZX81 is wrong, it should be 3.25 MHz, not 3.5."
Good hint, will change it.

"The image of the keyboard is blurry (low resolution). I have recreated the keyboard in a vector format. I put a version below in SVG."
That is great. If you put that in MIT license (or any free Common license) I would be happy to use it (of course with a credit).

" I can try to do the same for the ZX Spectrum if you find this useful."
Yes, same for this. An SVG image would be great.

**Comment by maziac** [comment]
I'm adding a "zx81-hires" simulation for the "ulaScreen".
It is working (the zx81 branch) but it does flicker a little bit.
Especially the  (ula) line counter seems to be off by 1 or 2, but not constant.
Do you have any idea what could be wrong with the simulation (Zx81UlaHiscreen)?
I must be missing some detail...

**Comment by andrivet** [comment]
Here is the ZX Spectrum keyboard in SVG.

![48k_kbd](https://github.com/user-attachments/assets/1ad123fa-e0a1-4fb9-9660-45fb6a1b90e7)

Both (ZX81 and ZX Spectrum keyboards SVG) are under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)

For Hires, I will look at it when I get some time.

**Comment by maziac** [comment]
The keyboard looks great!

"For Zx81UlaHiscreen, I will look at it when I get some time."
I looked into the implementation of zxsp. Probably the timing is not as accurate as required.
I will try to use the zxsp implementation.

**Comment by maziac** [comment]
Please check this commit for adding the keyboard files and the attribution: https://github.com/maziac/DeZog/commit/003bb1b57bf05fb0e5aca74acbce6516c15e0996

**Comment by andrivet** [comment]
👍

**Comment by maziac** [comment]
I was just thinking: The keypress boxes are now not aligned anymore with the svg.
Is there a way that I could directly use some svg id of the keys to get the size and draw the button press highlight with the size of the svg element. Not sure how to do that or integrate it with the html/js...
Maybe it is also possible to add the 'onClick' directly to the svg.
Would be more straightforward then to overlay it with html elements for the key presses.

**Comment by andrivet** [comment]
I don’t think it is possible.
What I can do is to modify the SVG to place keys exactly where they where in the PNG.

**Comment by maziac** [comment]
You don't have to. I probably have to adjust just a few offsets.

**Comment by andrivet** [comment]
And why not adding the QL like Spectrum keyboard, and the ZX80 one! Half joking…. One day, i am a little busy these days.

**Comment by maziac** [comment]
Could you please have a look. Seems the newline key is a little bit off the right margin.
![Bildschirmfoto 2024-08-27 um 22 08 46](https://github.com/user-attachments/assets/f1943de2-b888-4fef-aefc-7c9db2eaff1d)
I have changed the css so that it displays a red border around the available space.

**Comment by ped7g** [comment]
How about source level debug (SLD) data? I have on sjasmplus open [issue #232](https://github.com/z00m128/sjasmplus/issues/232) about what virtual device to use for zx80/81, and I'm not deeply familiar with these machines, but it still feels to me like classic ZXSPECTRUM48 should cover this use case too?

Maziac: I guess you will test DeZog with SLD for the ZX81? Let me know in case you are missing anything on sjasmplus side, and if you have some recommendation which sj virtual device to use for ZX80/81, so I close this thing and put it off my mind. :) TY.

**Comment by andrivet** [comment]
@ped7g use NOSLOT64K, it works for the ZX81

**Comment by maziac** [comment]
Yes, agree.

**Comment by andrivet** [comment]
This should be better:
![ZX81_keyboard](https://github.com/user-attachments/assets/4ede9743-1bb4-4c78-9b04-c4d058b503cf)

I can do the same for the Spectrum if you need it.

**Comment by maziac** [comment]
Everything fine, thanks. Both keyboards work now.

**Comment by andrivet** [comment]
I see you have solved the flickering in HiRes mode. I played with it a little (with PacMan in Pseudo HiRes for example), it works nicely.

**Comment by maziac** [comment]
Flickering is almost solved, but there is still a little bit remaining in Battlestar Galactica. Ist's non-hires, but if you play that with either hires or normal, there is sometimes still a little flicker.

**Comment by maziac** [comment]
I have analyzed  this a bit. After starting Galactica there is sometimes a little flickering when the 2nd or 3rd screen is created.
The screen is a dfile in **collapsed** format although this is using 16k or more.
![Bildschirmfoto 2024-09-02 um 18 39 59](https://github.com/user-attachments/assets/62ca7d47-b0b0-48a6-a3a1-73ffad093783)
I'm not sure how this can happen.
Maybe I'm initializing something wrong.

For a collapsed dfile I would think that some flickering is OK, because to extend a line there is some copying within the dfile required.
But the question is: why is the dfile collapsed?

**Comment by maziac** [comment]
OK, found it. It was whack I did for one game. Removed it and no flickering anymore.

**Comment by maziac** [comment]
I would like to simulate the memory mirroring as well. But I have not found any good documentation.
Do you know what is mirrored?
I think the ROM is mirrored at 0x2000, anything else?

**Comment by andrivet** [comment]
This is highly dependent on the RAMPack that is installed. A ZX81 with a classical 16K RAMPack mirrors the ROM at 0x2000, and the RAM (0x4000, 0x5FFF) at 0x8000.

Some RAMpacks are decoding the 0x2000-0x3FFF space to add 8K of RAM.
Some are also decoding higher addresses. to add even more RAM (data only). 
Some (64K RAMpacks) are even doing bank switching and allow replacing (after booting) the ROM by RAM. Here is for example the Manual of such (complex) RAMPack: https://archive.org/details/byte-back/Byte-Back%20UM-64%20manual/mode/2up

The number of variants is huge (see for example https://www.timexsinclair.com/blog/ram-packs-and-memory-expansion-for-the-zx81-and-ts1000/). You can even combine some (like 16K + 32K)

**Comment by andrivet** [comment]
I can check on the actual hardware if you think it is important. I have some Sinclair 16K RAMpacks somewhere. I should also receive a Memotech 32K RAMpack but I do not know when (I bought two ZX81 some days ago on eBay).

**Comment by maziac** [comment]
Thanks for the info. Probably it's not required to do tests on this (but thanks for the offer).

I was tinkering a little bit with the charset, i.e. replacing the original charset in dezog with a custom one to get better graphics for games and I'm pleased with the results, e.g.:
![image](https://github.com/user-attachments/assets/b26af604-1500-4c34-a9e9-1a8da0ddae36)

Do you know if there have been RAM packs around that allowed to change the charset with custom fonts? I.e. that put the charset in the RAM area.
The UM-64 above can copy the ROM to RAM, but the manual says changing the characters is not possible "the user cannot alter the character generator".
I.e. probably the ULA access is still routed elsewhere.

**Comment by andrivet** [comment]
The architecture of the ZX81 is unusual. It has two busses:
* One between the ULA and the ROM
* One between the CPU, the ROM and the RAM
This is why changing the characters in the mirror of the ROM in RAM does not change what the ULA is seeing,

There are however UDG (User defined graphics) extensions. They work by replacing the display routine in a way similar to WRX16 (high-resolution) tricks. 

There is also the CHR$(128) trick. The ROM contains only the graphics of the first 64 chars (+ the inverted ones) and they are defined at the end of the ROM. So if you use a higher code (>= 128), and if there is RAM at the right address, the ULA will use the graphics you defined.

**Comment by andrivet** [comment]
I see that some (true) hires programs are not working properly. It is probably not trivial to make them work. They are also not working correctly in emulators like ZEsarUX. They do display correctly in the EightyOne emulator and in the iOS ZX81 emulator.

The program ([Shogun](https://spectrumcomputing.co.uk/entry/32054/ZX81/Shogun) from Dr. Beep) :  [SHOGUN.P.zip](https://github.com/user-attachments/files/16922565/SHOGUN.P.zip)

In EightyOne:
<img width="1279" alt="Screenshot 2024-09-08 at 15 34 13" src="https://github.com/user-attachments/assets/cab61cec-04c5-477b-aa96-814d85042e65">

In DeZog:
<img width="884" alt="Screenshot 2024-09-08 at 15 36 04" src="https://github.com/user-attachments/assets/5539ef29-f3b3-48a2-af41-8ce674dcded0">

**Comment by andrivet** [comment]
ZEsarUX does display correctly with the right option activated (WRX):

<img width="694" alt="Screenshot 2024-09-08 at 16 35 52" src="https://github.com/user-attachments/assets/9730e354-26ad-45ef-9682-2090c6db3072">

**Comment by maziac** [comment]
Good catch. I will have a look.

**Comment by maziac** [comment]
Please check now. The ula simulation should support wrx now:
![Bildschirmfoto 2024-09-13 um 19 28 19](https://github.com/user-attachments/assets/6ab8a415-3d2a-406b-8587-d4513516c729)

**Comment by andrivet** [comment]
SHOGUN is working well now.

**Comment by maziac** [comment]
Meanwhile I also integrated ARX and chroma81 support.
Currently I'm working on chr$128/UDG.
There are quite a number of graphics modes...

**Comment by maziac** [comment]
@stevexyz I would like to use part of your code in https://github.com/z00m128/sjasmplus/issues/239#issuecomment-2336717630 in a loader wrapper I would like to publish on GitHub.
Is it MIT license?

**Comment by stevexyz** [comment]
> @stevexyz I would like to use part of your code in [z00m128/sjasmplus#239 (comment)](https://github.com/z00m128/sjasmplus/issues/239#issuecomment-2336717630) in a loader wrapper I would like to publish on GitHub. Is it MIT license?

For my part you can use the license you prefere, but let me ask also the original author if he is ok with it. Let you posted.

**Comment by stevexyz** [comment]
MIT license fine also for Lardo, even if he do not remeber furher the code origins. cfr: https://sinclairzxworld.com/viewtopic.php?p=56796#p56796
What I can say is that is so simple program that should not be a problem.

**Comment by maziac** [comment]
Fine. Thanks.

**Comment by maziac** [comment]
Here is a release candidate for the 3.5.0 DeZog (ZX81):
https://github.com/maziac/DeZog/releases/tag/untagged-3e63a966abeac6bdde0f

The ZX81 sample project (with the BASIC wrapper to create a p-file) is here:
https://github.com/maziac/zx81-sample-program

If you would like to test it I would be happy get your error reports (or success stories :-) ).

**Comment by andrivet** [comment]
It is working pretty well. 

The only cases where the simulation is not working 100% are with binaries that push the ZX81 to its limits. A notable example is [25THANNI](https://worldofspectrum.net/item/0031996/), a demo that includes source code. ZesarUX is working a little better but not completely. The only simulator I am aware of that works 100% is the [iPadOS / macOS ZX81 simulator](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://apps.apple.com/us/app/zx81/id1180117434&ved=2ahUKEwiulNKhtfeIAxV7if0HHRICBJEQFnoECBwQAQ&usg=AOvVaw18eWInkx7EVjE1-uEZLzOV).

In this part of the demo, some text is drawn outside of the regular area:
<img width="615" alt="Screenshot 2024-10-05 at 16 11 07" src="https://github.com/user-attachments/assets/874018fb-58f4-4429-8b73-d499d67d9fbd">

Your simulated display is cropped so it does not show those lines:
<img width="792" alt="Screenshot 2024-10-05 at 16 14 10" src="https://github.com/user-attachments/assets/fb3f585f-1d9e-4478-acd1-accc18f126db">

Another step displays a bouncing ball (press Space to go from one step to the next):
<img width="615" alt="Screenshot 2024-10-05 at 16 11 35" src="https://github.com/user-attachments/assets/d830c3aa-becf-4a34-8a08-96b7b1778bcc">

Your simulation does display it but the ball is confined to the left:
<img width="792" alt="Screenshot 2024-10-05 at 16 15 41" src="https://github.com/user-attachments/assets/e156c9e9-9e06-4f3b-9ef5-9cf4a06251e1">

It is the same for the other steps.

**Comment by andrivet** [comment]
On the success side, my game is working very well in your simulator. I wrote the original version in 1985; seeing it running in modern tools is a particular feeling.

<img width="2560" alt="Screenshot 2024-10-05 at 16 21 37" src="https://github.com/user-attachments/assets/6cb0a4be-955c-4200-9f9d-ee439bca3538">

**Comment by maziac** [comment]
Thanks for the thoroughly testing.
I will have a look.

**Comment by maziac** [comment]
About yor game: you still have the assembler code?
And you had an assembler those days?

**Comment by andrivet** [comment]
I have reversed engineered it some years ago (it was published in a journal in the ‘80 so I can get the binary back thanks to that). Last year, I documented the assembly and was able to fix a bug I was not able to fix 40 years ago. And yes  in the ‘80, I had an assembler for this processor and machine.

**Comment by maziac** [comment]
"And yes in the ‘80, I had an assembler for this processor and machine."
Lucky you. Those days I created my games by just using an hex editor.
I didn't even know that something like assemblers exist.
Some of the opcode numbers I still do remember...

**Comment by andrivet** [comment]
At some point, I decided to buy an assembler. Before that, I computed opcodes by hand, on paper. I think it was this one: http://www.zx81stuff.org.uk/zx81/tape/ZXAssembler

![](http://www.zx81stuff.org.uk/zx81/inlays/z/ZXAssembler.Cover.jpg)

**Comment by stevexyz** [comment]
> Here is a release candidate for the 3.5.0 DeZog (ZX81): https://github.com/maziac/DeZog/releases/tag/untagged-3e63a966abeac6bdde0f


I tried to install it, but not sure why debugger is not starting.
After Run->Start Debugging and selecting dezog nothing happen...

There is a way to enable and see some trace?

Since it might depend on the launch.json configuration, can you please provide an example compatible with the helloworld discussed above?  (surely useful to complete the sample package!)

**Comment by maziac** [comment]
Sure. you can find an example here:
https://github.com/maziac/zx81-sample-program
It is re-faactored but working very similar to the helloworld.zip.
It also comes with a readme/explanations.

**Comment by stevexyz** [comment]
Sample program is working fine!!
With the internal debugger Dezog has become a gorgeous ZX81 IDE!!
Compliment for the superb work!!

**Comment by maziac** [comment]
🙏

**Comment by maziac** [comment]
Hi @stevexyz , Hi @andrivet ,

I have worked for some time on something else for ZX81 development.
Maybe you are interested to test.
It is another extension that allows to view p-files, convert to .bas (BASIC) files and convert back to .p files.

Please find here some screenshots:

![Bildschirmfoto 2024-10-20 um 12 38 21](https://github.com/user-attachments/assets/cb600cef-39c2-45ab-bc6c-d2ec34db4baa)
![Bildschirmfoto 2024-10-20 um 12 38 46](https://github.com/user-attachments/assets/5946dd96-f5c3-4195-a509-922e9427c9c2)

Convert to BASIC:
![Bildschirmfoto 2024-10-20 um 12 38 59](https://github.com/user-attachments/assets/4e35e6a3-94b6-4da4-b971-f2afc3020670)
![Bildschirmfoto 2024-10-20 um 12 39 17](https://github.com/user-attachments/assets/c6646dec-162e-4f41-b8ae-2a7430c3a1ea)
![Bildschirmfoto 2024-10-20 um 12 39 47](https://github.com/user-attachments/assets/9176d410-2868-4668-9194-be52ca6b7259)

Modify the BASIC:
![Bildschirmfoto 2024-10-20 um 13 04 47](https://github.com/user-attachments/assets/ed086e0c-4477-4f3e-b9bb-6227ff94ea17)
![Bildschirmfoto 2024-10-20 um 13 05 13](https://github.com/user-attachments/assets/c1c8229d-77a8-44a6-9a88-ac14c47727d4)

Convert back to .p:
![Bildschirmfoto 2024-10-20 um 12 40 02](https://github.com/user-attachments/assets/85d11704-0089-47be-811e-ff642af31935)

And load into dezog:
![Bildschirmfoto 2024-10-20 um 13 07 23](https://github.com/user-attachments/assets/9e0b3da9-cfd6-493e-a5f6-af5ac64425cf)

I have tested already with a few files and it seem to work quite well. E.g Mazogs, 3D Monster Maze. Not working is "Against the elements" but I guess it uses some special hack.

If you would like to try:
[zx81-bastop-1.0.0-rc1.vsix.zip](https://github.com/user-attachments/files/17449997/zx81-bastop-1.0.0-rc1.vsix.zip)

Any feedback appreciated...

**Comment by maziac** [comment]
Here is an updated version:
[zx81-bastop-1.0.0-rc2.vsix.zip](https://github.com/user-attachments/files/17464943/zx81-bastop-1.0.0-rc2.vsix.zip)

**Comment by maziac** [comment]
I didn't do much with the BASIC either but I wanted an option to "disassemble" one of my old projects, do changes and "reassemble" it.

**Comment by andrivet** [comment]
This is really awesome. I will test it.

**Comment by maziac** [comment]
@andrivet Had a hard time with 25thanni, but now it seems to work.
Please see here for the rc3 release: https://github.com/maziac/DeZog/releases/tag/untagged-3e63a966abeac6bdde0f
and let me know if you still see issues.
(Please note that a few launch.json parameters have changed, please have a look at the [zx81-zsim.md](https://github.com/maziac/DeZog/blob/main/documentation/zx81/zx81-zsim.md].

![Bildschirmfoto 2024-11-01 um 13 39 10](https://github.com/user-attachments/assets/51e37be7-b4e7-4b45-9920-9bc2971e61fd)

![Bildschirmfoto 2024-11-01 um 15 08 33](https://github.com/user-attachments/assets/d6421e41-050b-4775-8fb1-a7c0f5e78385)

**Comment by andrivet** [comment]
The simulation of the ULA display is so good now. Mind blowing!

**Comment by maziac** [comment]
Thanks. It took me a while. For this demo to work I really had to go down to the single t-states.
Longest time took me the simulation of the "wait circuit". Not the simulation itself, but to understand that it was missing.

I'm about to release the 3.5 dezog, do you think anything is missing?

(BTW today I also released the p-file viewer (BASIC to P converter).)

**Comment by andrivet** [comment]
I have in my (long) list of future projects the idea to recreate the ULA in an FPGA and make it open source (such ULAs do already exist but are closed source). Your wonderful work will help me with those tiny details.

>  I'm about to release the 3.5 dezog, do you think anything is missing?

I think it is ready.

> (BTW today I also released the p-file viewer (BASIC to P converter).)

I just star  it.

**Comment by andrivet** [comment]
Something that is currently missing is the copyright for the ZX81 ROM in the Readme.

**Comment by maziac** [comment]
Thanks, for the hint.

**Comment by maziac** [comment]
I close the Issue now.
The ZX81 simulation is integrated in DeZog v3.5.0 and has been released today.
If you find anything else please report a new issue.

Thank you both for all the help and testing.
