### ISSUE TITLE
Testing the beta-13.3

### ISSUE THREAD

**Issue by mnunesvsc** [maziac/DeZog#13]
Tried to start the debugger, but the .tap not load, so i did the instructions, and the debugger paused, but this happened 

![image](https://user-images.githubusercontent.com/205459/77264673-9b442b00-6c79-11ea-8c1b-334eccc1d91d.png)

**Version etc. (please complete the following information):**
 - SW 13.3: 
 - OS: windows 7 8 gb mem 
 - ZEsarUX 8.1 Version: 

**Additional context**
.launch.json 
{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "dezog",
            "request": "launch",
            "name": "Speccy Tron",
            "remoteType": "zrcp",
            "zrcp": {
                "hostname": "localhost",
                "port": 12000
            },            
            "listFiles": [
                {
                    "path": "speccytron.c.lis",
                    "sources": "speccytron.c.lis",
                    "useFiles": true,
                    "asm": "z88dk",
                    "mainFile": "speccytron.c",
                    "srcDirs": [],
                    "addOffset": 32768
                }
            ],
            "startAutomatically": false,
            "skipInterrupt": true,
            "commandsAfterLaunch": [
                //"-sprites",
                //"-patterns"
            ],
            "disassemblerArgs": {
                "esxdosRst": true
            },
            "rootFolder": "${workspaceFolder}",
            "load": "speccytron5.tap",
            // "load": "4.Z80",
            "smallValuesMaximum": 512,
            "tmpDir": ".tmp"
       },
       {
        "type": "dezog",
        "request": "launch",
        "name": "efd",
        "remoteType": "zrcp",
        "zrcp": {
            "hostname": "localhost",
            "port": 12000
        },            
        "listFiles": [
            {
                "path": "efd.c.lis",
                "sources": "efd.c.lis",
                "useFiles": true,
                "asm": "z88dk",
                "mainFile": "efd.c",
                "srcDirs": [],
                "addOffset": 32768
            }
        ],
        "startAutomatically": false,
        "skipInterrupt": true,
        "commandsAfterLaunch": [
            //"-sprites",
            //"-patterns"
        ],
        "disassemblerArgs": {
            "esxdosRst": true
        },
        "rootFolder": "${workspaceFolder}",
        "load": "efd.tap",
        "smallValuesMaximum": 512,
        "tmpDir": ".tmp"
    },
    ]
}

**Comment by maziac** [comment]
The v0.13.3 was a test release to hunt down the zesarux crash problem.
It has side-effects.
You can try out the 0.13.4 https://github.com/maziac/DeZog/releases/tag/v0.13.4 .
It has automatic loading enabled again.
