### ISSUE TITLE
ZX81 keyboard: highlighting of keys is shifted

### ISSUE THREAD

**Issue by andrivet** [maziac/DeZog#134]
**Describe the bug**

When you press (on the screen or keyboard) a key on the right, the highlight is shifted.

**To Reproduce**
1. Start a ZX81 program such as zx81-sample-program
2. Start the debugging
3. Press 0

**Expected behavior**
The highlight should be aligned with the key

**Screenshots**
<img width="696" alt="image" src="https://github.com/user-attachments/assets/a2814390-517f-4cd5-bd99-e894e52ae238">

**Version etc. (please complete the following information):**
 - DeZog SW Version:  3.6.0
 - OS: macOS
 - Remote: zsim or zrcp (ZEsarUX): zsim

**Comment by maziac** [comment]
Thanks for reporting. That was working, but I remember that I changed the aspect ratio afterwards. That certainly broke it.

**Comment by maziac** [comment]
Fixed in 3.5.1
