### ISSUE TITLE
[Feature Request] Add 128K memory layout in zsim

### ISSUE THREAD

**Issue by kborowinski** [maziac/DeZog#14]
Currently *zsim* displays ZX Spectrum Next 8K memory layout. Would it be possible to add ZX Spectrum 128 16K memory layout. It could be in a form of small sub-bar or extra row of annotations

![image](https://user-images.githubusercontent.com/16168755/77854413-9b4ca980-71ea-11ea-8578-a06c1a86cccb.png)

**Comment by maziac** [comment]
Please try the latest gihub and choose:
"visualMemory": "ZX128"

**Comment by kborowinski** [comment]
Thanks, this's exactly what I was looking for.
