### ISSUE TITLE
[Feature Request] Display PC register and T-States in zsim debug console

### ISSUE THREAD

**Issue by kborowinski** [maziac/DeZog#16]
Please consider adding PC register and execution time (T-States) to *zsim* debug console output (similarly to Zesarux remote debugging output).

*Note:*
In case of the **CALL [C,NC,Z,NZ,M,P,PE,PE]** instruction the T-States should display total execution time of called branch (see picture)

![dezog_zsim](https://user-images.githubusercontent.com/16168755/78359591-a79f8080-75b5-11ea-877a-76c6b27c18e7.jpg)

**Comment by maziac** [comment]
Just a hint:
You can view the PC and instructions also in the VARIABLES view:
![Bildschirmfoto 2020-04-03 um 16 56 28](https://user-images.githubusercontent.com/3081973/78374761-361efc80-75cc-11ea-896a-a671de86b7f0.jpg)

**Comment by kborowinski** [comment]
So then maybe just add T-States to the Disassembly view? And is there a way to increase the disassembly size from 8 instructions?

**Comment by maziac** [comment]
I can add the PC output most probably also to the debug console, just wanted to make you aware of that view.

More than 8 instructions: how many do you have in mind?
I could probably make this configurable but this is brute-force disassembly.
I.e. as soon as some data comes in the way it is decoding data as instructions. So the probability for this to happen increases for a big number of instructions.

**Comment by kborowinski** [comment]
If you can add T-State output to the debug console then there's no need to increase the disassembly view.

**Comment by maziac** [comment]
Done (at least in develop branch).
![Bildschirmfoto 2020-04-30 um 13 46 27](https://user-images.githubusercontent.com/3081973/80706689-fffc6c00-8ae8-11ea-9519-602d86efede7.jpg)
