### ISSUE TITLE
c.lis file never being used, always auto disasm.asm

### ISSUE THREAD

**Issue by mnunesvsc** [maziac/DeZog#17]
Anytime i try to debug a code, compiled on z88dk, and running, the disassemble not use the c.lis generated, some early versions it worked, but not anymore

![image](https://user-images.githubusercontent.com/205459/78468495-03215980-76ef-11ea-85d5-4c5b0724174b.png)

 - DeZog 1.1.0: 
 - OS: windows 7 64 , 8gb ram 
 - Remote: zrcp (ZEsarUX): 8.1-B2 

follows my launch options, early versions, if i change 
asm: option

 it worked, and no change in files or sources do the slight difference.

i put the complete launch, but the one with the issue is;

**DeZog raiz**

{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "dezog",
            "request": "launch",
            "name": "DeZog raiz",
            "remoteType": "zrcp",
            "zrcp": {
                "hostname": "localhost",
                "port": 12000
            },
            "zsim": {
                "machine": "48k"
            },
            "serial": {
                "baudrate": 230400,
                "port": "/dev/tty.usbserial"
            },
            // "topOfStack": "stack_top",
            "listFiles": [
                {
                    "sources": "efd.c.lis",
                    "useFiles": true,
                    "asm": "z88dk",
                    "srcDirs": [],
                    "path": "efd.c.lis",
                }
            ],
            "disassemblerArgs": {
                "esxdosRst": true
            },
            "load": "efd.tap",
            "skipInterrupt": true
        },

        {
            "type": "dezog",
            "request": "launch",
            "name": "Speccy Tron",
            "remoteType": "zrcp",
            "zrcp": {
                "hostname": "localhost",
                "port": 12000
            },            
            "listFiles": [
                {
                    "path": "speccytron.c.lis",
                    "sources": "speccytron.c.lis",
                    "useFiles": true,
                    "asm": "z88dk",
                    "mainFile": "speccytron.c",
                    "srcDirs": [],
                    "addOffset": 32768
                }
            ],
            "startAutomatically": false,
            "skipInterrupt": true,
            "commandsAfterLaunch": [
                //"-sprites",
                //"-patterns"
            ],
            "disassemblerArgs": {
                "esxdosRst": true
            },
            "rootFolder": "${workspaceFolder}",
            "load": "speccytron5.tap",
            // "load": "4.Z80",
            "smallValuesMaximum": 512,
            "tmpDir": ".tmp"
       },
       {
        "type": "dezog",
        "request": "launch",
        "name": "efd",
        "remoteType": "zrcp",
        "zrcp": {
            "hostname": "localhost",
            "port": 12000
        },            
        "listFiles": [
            {
                "path": "efd.c.lis",
                // "sources": "efd.c",
                "useFiles": true,
                "asm": "z80asm",
                // "listfiles": "efd.c.lis, dbalib.c.lis",
                "mainFile": "efd.c.lis",
                // "srcDirs": [],
                "addOffset": 25124
            }
        ],
        "startAutomatically": false,
        "skipInterrupt": true,
        "commandsAfterLaunch": [
            //"-sprites",
            //"-patterns"
        ],
        "disassemblerArgs": {
            "esxdosRst": true
        },
        "rootFolder": "${workspaceFolder}",
        "load": "efd.tap",
        "smallValuesMaximum": 512,
        "tmpDir": ".tmp"
    }
    ]
}

**Comment by maziac** [comment]
Could you attach your project here, so I can reproduce.

**Comment by maziac** [comment]
I looked at your launch.json. Maybe that helps already.

"sources" is not used at all anymore by DeZog. I have now seen that it is still included in the configuration snippet, so I will remove it there.

In the raiz configuration you didn't put in any "mainFile". I guess this is the reason why you cannot do source-level debugging.

In the Speccy Trom configuration I have seen that you put in
                "mainFile": "speccytron.c"
This is a c-file I guess. So I don't think that it can work. DeZog expect asm sources here.
If it really works please let me know, this was unintended (but would be really great).

**Comment by mnunesvsc** [comment]
Wow, thanks for the answers, i did was told, but not loading, but i got a different error, 
please not pay attention to the others launch options, "Raiz" is the only used

![image](https://user-images.githubusercontent.com/205459/78502988-45bc5380-773a-11ea-8af4-32058dd4beb4.png)

**Comment by mnunesvsc** [comment]
sorry the picture not go complete 

![image](https://user-images.githubusercontent.com/205459/78503019-756b5b80-773a-11ea-871f-f24cba842abf.png)

**Comment by maziac** [comment]
If that didn't help then please provide me with the project or some minimal test program.
(I did test my z88dk test project and that was working).

**Comment by mnunesvsc** [comment]
Luckyly speccy is small :) if in need of anything more tell me 

[speccytron.zip](https://github.com/maziac/DeZog/files/4434258/speccytron.zip)

**Comment by mnunesvsc** [comment]
by the way this is reporting too, this error 

![image](https://user-images.githubusercontent.com/205459/78504095-3b518800-7741-11ea-8c75-6c3e575c7354.png)

**Comment by maziac** [comment]
Hi, I got it working somehow:
![Bildschirmfoto 2020-04-05 um 18 28 39](https://user-images.githubusercontent.com/3081973/78504198-b891f280-776b-11ea-89d8-9f680e657db0.jpg)

You need to change your listFiles section such:

~~~
"listFiles": [
                {
                    "path": "efd.c.lis",
                    "useFiles": false,
                    "asm": "z88dk",
                    //"mainFile": "efd.c.lis",
                    "addOffset": 25124,
                    "srcDirs": []                }
            ],
~~~

Explanation:
You don't have asm source files only an assembler list file therefore you have to choose "useFiles": false.
This means: your list file only, no assembler source files.
Furthermore remove "mainFile". This is normally the main assembler source file. You have none so nothing should be specified here.
Then: It is working, i.e. it uses your list file and shows it, i.e. you can step. But the lines do not match what you see in the "Disassembly" view. This probably means that your offset ("addOffset") is wrong. Maybe you need to experiment with other values here. Or maybe the tap file didn't exactly match the included list file.

You are currently using a tap file as output. That is fine. But it requires zesarux to go through the ZX ROM and "load" the file. If you have the chance to use the SNA or NEX file format this would not be required, i.e. the loading works more smooth.

Further note:
I didn't see the "Illegal operation" or ZEsarUX errors. But I'm working on macOS. If it persists for you please report.

**Comment by maziac** [comment]
Aah, I forgot: It's normal that you start with a disassembly at 0000h. This is because of that tap loading.
You would need to put a breakpoint somewhere in your list file and run from 0000h.

**Comment by mnunesvsc** [comment]
Did the instructions, and if on debbug i do an step, it goes to the file, but as long i hit go and pause he got back to disasm, i generated the .sna and changed the launch, sending again 

![image](https://user-images.githubusercontent.com/205459/78505098-8cfd1100-7747-11ea-97e0-71e89398f44b.png)

![image](https://user-images.githubusercontent.com/205459/78505122-aa31df80-7747-11ea-888b-c6be247555d8.png)

[speccytron.zip](https://github.com/maziac/DeZog/files/4434398/speccytron.zip)

**Comment by mnunesvsc** [comment]
I have success in setting a breakpoint in file and the debbug stoped right, but if i dig into, he cannot find the lib ( dbalib.c.lis ) and show me a fuzzy code ( not the one in .c.lis ) and return.

pointg that because it is the routine i need to know why is not workig :)

sorry for the trouble.

![image](https://user-images.githubusercontent.com/205459/78505394-9be4c300-7749-11ea-8c0f-4a19811754c4.png)

![image](https://user-images.githubusercontent.com/205459/78505410-b0c15680-7749-11ea-9c54-d96cab2de709.png)

the code is the same, of the previously comment.

**Comment by mnunesvsc** [comment]
more info, if i change the asm from; 

z80asm 

to 

z88dk

it cannot set the breakpoints, nor show the main c.lis file, only works for me with z80asm, and it is the only option in sugestion.

![image](https://user-images.githubusercontent.com/205459/78505619-077b6000-774b-11ea-8df4-2696f022590b.png)

![image](https://user-images.githubusercontent.com/205459/78505633-15c97c00-774b-11ea-9cd2-0192a4660887.png)

hope this could help

**Comment by maziac** [comment]
The z80asm option is for Savannah's z80asm.
For z88dk use "z88dk". Unfortunately z88dk used the same name for its assembler.

I think I need some more time to sort this out.
It has something to do with the "addOffset". Do you know what the ORG for your source code is,
e.g. where the _loadlevel is supposed to be?

The list files of z88dk are not very easy to read as all sections start at 0000h although they are located at some real addresses.

**Comment by mnunesvsc** [comment]
Thankyou for the help, unfortunally i do not possess the knowledge of the inards of the z88dk, but the only thing out of the code, c.lis is the pragma i used hope this help somehow 

// definitions 
#pragma output STACKPTR              = 53248      // place stack at $d000 at startup
#pragma output REGISTER_SP           = 0xd000    // place stack at $d000 at startup
#pragma output CLIB_MALLOC_HEAP_SIZE = 3000      // create a 3000-byte heap in BSS section
#pragma output CLIB_EXIT_STACK_SIZE  = 0         // no atexit() functions
#pragma output CLIB_STDIO_HEAP_SIZE  = 0         // no memory for files
#pragma output CLIB_FOPEN_MAX        = -1        // do not create open files list
// COMPILE TIME CRT CONFIGURATION

#pragma output CRT_ORG_CODE           = 25124      // org of compile
// #pragma output CRT_ORG_CODE          = 32768     // org 32768
#pragma output CRT_ENABLE_CLOSE       = 0          // don't bother closing files on exit
#pragma output CRT_ENABLE_EIDI        = 0x1        // disable interrupts at start
// #pragma output CRT_ON_EXIT            = 0x30002    // return to basic on exit

#pragma output CLIB_MALLOC_HEAP_SIZE  = 0          // no malloc heap
#pragma output CLIB_STDIO_HEAP_SIZE   = 0          // no stdio heap (no files)

#pragma output CLIB_FOPEN_MAX         = -1         // no FILE* list
#pragma output CLIB_OPEN_MAX          = -1         // no fd table
// CREATE A BLOCK MEMORY ALLOCATOR WITH ONE QUEUE
// #pragma output CLIB_BALLOC_TABLE_SIZE = 1

**Comment by mnunesvsc** [comment]
And the command line i use to compile the code, if i can be of any more help. 

set PATH=C:\z88dk\bin;%PATH%
set ZCCCFG=C:\z88dk\lib\config
set TEMP=.temp
set TMP=.temp

rem compile all  
zcc +zx -vn --opt-code-speed -SO3 -clib=sdcc_iy -startup=31 --max-allocs-per-node2000 @efd.lst -m --list --c-code-in-asm -oefd -create-app -Cz"--sna"

**Comment by maziac** [comment]
What seems to work is the address offset 30520

~~~
            "listFiles": [
                {
                    "path": "efd.c.lis",
                    "useFiles": false,
                    "asm": "z88dk",
                    // "mainFile": "efd.c.lis",
                    "addOffset": 30520, //25281,
                    "srcDirs": []
                }
~~~

I have taken it from the lis and map file.
The code section in the lis file starts with _loadlevel. The lis file includes only relative addresses so it starts with address 0000.
The map file shows that this maps to $7738 which is 30520.

Start the debug session, you land in some disassembled code. 
Set a breakpoint at '_main' in your lis file.
Do a 'run'.
You will end up here in the lis file:
![Bildschirmfoto 2020-04-06 um 09 36 23](https://user-images.githubusercontent.com/3081973/78534227-5debab80-77ea-11ea-9122-9a967499ba62.jpg)

Although this seems to work for the code section there is a problem with the other labels.
I.e. the data labels like _off_screen also start at relative address 0000. The offset is added to them as well.
This results in _off_screen == _loadlevel which is not true if you look at the map file.
I.e. you can't rely on the label resolution for your data.

I will need to think a bit if I can work around this (otherwise I need to drop official support for z88dk).

**Comment by maziac** [comment]
I have created a new release v1.1.1, please get it here:
https://github.com/maziac/DeZog/releases/tag/v1.1.1

Please download and install via the vscode command palette (Press F1) and choose "Extensions: install from VSIX...". 

The addresses now seem to work correctly but you need to add a new parameter.
Use this:
~~~

            "listFiles": [
                {
                    "path": "efd.c.lis",
                    "asm": "z88dk",
                    "srcDirs": [],
                    "z88dkMapFile": "efd.map"
                }
            ],
~~~
I.e. the map file is added here. It allows to associate the labels with the line numbers in the lis file.
The "addOffset" is gone. Don't use it together with "z88dkMapFile". It will not work.

As before:
Start the debug session, you land in some disassembled code.
Set a breakpoint at '_main' in your lis file.
Do a 'run'.

Now you should be in your lis file instead of the disasm.asm.

**Comment by mnunesvsc** [comment]
Testing the release, if i use z88dk this happen.

![image](https://user-images.githubusercontent.com/205459/78590097-aa99ab80-7817-11ea-9ee9-da01203575ac.png)

if i use z80asm the c.lis is not loaded, even if i set a breakpoint.

![image](https://user-images.githubusercontent.com/205459/78590229-e16fc180-7817-11ea-8647-2f86c2894774.png)

P.S. Again the warning for the parameter; cpu-history ignorephalt yes => Error. Unknow parameter


[speccytron.zip](https://github.com/maziac/DeZog/files/4440058/speccytron.zip)

**Comment by maziac** [comment]
As said, you need to remove "addOffset" completely. Please try again.

And: You don't need to tinker around with "z80asm". It is a different assembler.

**Comment by mnunesvsc** [comment]
do not even start 

![image](https://user-images.githubusercontent.com/205459/78592255-306b2600-781b-11ea-9c3d-68c61bdde0f9.png)

**Comment by maziac** [comment]
I don't think that Skype will help. I need to debug the problem.
Could you once again zip your project.

**Comment by mnunesvsc** [comment]
> I don't think that Skype will help. I need to debug the problem.
> Could you once again zip your project.

i did, on a post before, it is on a zip, + map, and lis

**Comment by maziac** [comment]
I could reproduce it now. You are missing the "srcDirs": [] from my post.

Please use exactly this "listFiles" properties. No additions, no left outs:
~~~
            "listFiles": [
                {
                    "path": "efd.c.lis",
                    "asm": "z88dk",
                    "srcDirs": [],
                    "z88dkMapFile": "efd.map"
                }
            ],
~~~

**Comment by mnunesvsc** [comment]
nope.. 

![image](https://user-images.githubusercontent.com/205459/78664764-0b25f880-78ab-11ea-9fff-31926f602f94.png)

directly to disasm, do not even open the .clis file 

![image](https://user-images.githubusercontent.com/205459/78664828-2b55b780-78ab-11ea-84f0-47253c85e177.png)

**Comment by mnunesvsc** [comment]
can be any relation with that rootdir ? 

![image](https://user-images.githubusercontent.com/205459/78664944-67891800-78ab-11ea-887f-c8b93e76cdc3.png)

**Comment by maziac** [comment]
I prepared a new release
https://github.com/maziac/DeZog/releases/tag/v1.1.2-pre1
to make sure that we are working with exactly the same version.

If that does not help then please send me your zipped project once again. There must be something different.
Your old project is working fine for me now.

**Comment by mnunesvsc** [comment]
not work same behavior

![image](https://user-images.githubusercontent.com/205459/78681600-5946f600-78c3-11ea-9bbc-fb4cf7d0105e.png)


[speccytron.zip](https://github.com/maziac/DeZog/files/4445147/speccytron.zip)

**Comment by maziac** [comment]
The zip is missing  the .vscode folder, i.e. the launch.json.

**Comment by mnunesvsc** [comment]
My bad, here goes 

[speccytron.zip](https://github.com/maziac/DeZog/files/4445608/speccytron.zip)

**Comment by maziac** [comment]
I could change it so that it works.
Again: Don't use "z80asm". This property is used for Savannah's assembler listing syntax.
It has nothing in common with z88dk-z80asm besides the name.
For z88dk-z80asm use "z88dk".

That was in fact the only line that I changed.
Here is an animated gif and I attached the changed project below.

![speccytron](https://user-images.githubusercontent.com/3081973/78695734-c2982a80-78fe-11ea-8fd2-84b792ac1ad8.gif)

[speccytron.zip](https://github.com/maziac/DeZog/files/4445921/speccytron.zip)

**Comment by mnunesvsc** [comment]
This is what happens to me 

![image](https://user-images.githubusercontent.com/205459/78705737-4ee92400-78e4-11ea-9cc4-e8c1456f68ed.png)

**Comment by maziac** [comment]
Interesting issue.
I have now run into a similar problem: sometimes, when I set an breakpoint it is not set, i.e. it is "unverified".
That means the Z80-address to file-line association has gone wrong.
Have you really used the speccytron.zip that I attached. Especially rootFolder should be  "${workspaceFolder}"?

I have prepared a new version 1.1.2-pre2 here which has additional debug output:
https://github.com/maziac/DeZog/releases/tag/v1.1.2-pre2

Could you please install it and start a debug session.
Then at line 1498 (push ix)
![Bildschirmfoto 2020-04-08 um 08 26 48](https://user-images.githubusercontent.com/3081973/78751542-bcdc2c80-7972-11ea-8a7b-4124bcb05e32.jpg)
set a breakpoint and make a screenshot of the DEBUG CONSOLE.
You should get something similar to this:
![Bildschirmfoto 2020-04-08 um 08 28 38](https://user-images.githubusercontent.com/3081973/78751682-fa40ba00-7972-11ea-82dc-ec06e963a1ae.jpg)

**Comment by mnunesvsc** [comment]
The initial operation worked as predicted, BUT.... 

![image](https://user-images.githubusercontent.com/205459/78844607-93f08180-79dc-11ea-8da2-293051891005.png)

![image](https://user-images.githubusercontent.com/205459/78844701-e336b200-79dc-11ea-8b56-dc40a2dac6b8.png)

as the images shows no output on the screen, on the output tab 

and as i pause, on the interface, they return to the disasm.asm 

![image](https://user-images.githubusercontent.com/205459/78844668-cc905b00-79dc-11ea-8714-000e04086845.png)
 
hope this help

[speccytron.zip](https://github.com/maziac/DeZog/files/4453333/speccytron.zip)

**Comment by maziac** [comment]
Actually this looks good.

**- "as the images shows no output on the screen, on the output tab":**
This is because you are on the OUTPUT tab. Please change to the DEBUG CONSOLE to see the output I meant (the output when setting a breakpoint).
But as I can see the breakpoints are verified now. I.e. working correctly. So the output would not help here.
But please, as soon as you run into this problem again (a breakpoint cannot be set in your lis file) then check the DEBUG CONSOLE and send me a screenshot. 
I suspect that sometimes something is going wrong there.

**- "and as i pause, on the interface, they return to the disasm.asm":**
This is correct behavior.
It is simply because there is no source code provided for that memory area. In that case the internal disassembler jumps in and shows the disasm.asm code.
Have a look at your efd.c.lis file and search e.g. for "_drawSpriteM". It is used by some calls but not defined in end.c.lis. Thus DeZog does not know about it.
Luckily you can tell DeZog to use several list files like so:
~~~

            "listFiles": [
                {
                    "path": "efd.c.lis",
                    "asm": "z88dk",
                    "srcDirs": [],
                    "z88dkMapFile": "efd.map"
                },
                {
                    "path": "dbalib.c.lis",
                    "asm": "z88dk",
                    "srcDirs": [],
                    "z88dkMapFile": "efd.map"
                }
            ],
~~~

"_drawSpriteM" is included in "dbalib.c.lis" and now DeZog can find it.
If you now do a break you probably land in known source code.
![Bildschirmfoto 2020-04-09 um 08 24 28](https://user-images.githubusercontent.com/3081973/78864254-90401780-7a3b-11ea-87e6-c6f3d4fc5893.jpg)
If you have more lis files you should add them probably as well.

**Comment by mnunesvsc** [comment]
WORKED like a charm, sorry for all the trouble  

goes inside the other lib, AWESOME 

![image](https://user-images.githubusercontent.com/205459/78913821-f6d72c80-7a5f-11ea-8f71-6c9be3200470.png)

![image](https://user-images.githubusercontent.com/205459/78913885-11110a80-7a60-11ea-838b-95d5c291f0db.png)

thank you for the hard work and the excellent tool.

**Comment by maziac** [comment]
That's nice to hear.
And thanks for your support as well.
This made the z88dk support a bit better.

And thanks for the offer. Any testing is always appreciated.

**Comment by mnunesvsc** [comment]
Thanks for the fast responses, and hard working, closing the issue

**Comment by Blackbelt61** [comment]
Hi,
I have followed this interesting and useful thread because I am trying to use DeZog with z88dk.

With the hints and explanations in this thread I have been able to prepare an environment for compiling and debugging my z88dk projects, but there is still a problem that I am not able to solve:
even if I am including the .map and .lis files in my launch.json, I can see the code listing while I am debugging, but all the breakpoints are always unverified.

Here is the error I get in the Debug console:

Unverified breakpoint:{"verified":false,"line":996,"column":0,"source":{"name":"TestLists2.c.lis","path":"n:\\DGT_LIB\\Examples\\TestLists2\\Sources\\TestLists2.c.lis","sourceReference":0}}

and attached you can find my project (the folder that has to be opened with VSC is "N:\TestLists2.zip\N\DGT_LIB\Examples\TestLists2").

I am sure I am making something wrong, but I don't know what.

Thank you in advance for any help you cah give here.


[TestLists2.zip](https://github.com/maziac/DeZog/files/4707617/TestLists2.zip)

**Comment by maziac** [comment]
Hi, I can have a look but your zip misses the .vscode folders, I think.
Could you include them as well.
Regards.

**Comment by Blackbelt61** [comment]
Hi @maziac 
you are right, sorry.

Here is the .zip file again with the .vscode folder included.
You can find it in N:\DGT_LIB\Examples\TestLists2

Thanks


[TestLists2.zip](https://github.com/maziac/DeZog/files/4707723/TestLists2.zip)

**Comment by maziac** [comment]
I tested it now but I don't think there is any problem with your setup.
I was able to set breakpoints. Maybe you used the wrong file.
Don't set the breakpoints in the TestLists2.lis file but e.g. in TestLists2.c.lis.

When I startup I end up here. That's some preamble code of your compiler.
![Bildschirmfoto 2020-05-31 um 23 37 06](https://user-images.githubusercontent.com/3081973/83363214-e4121180-a397-11ea-8734-2e51a096defa.jpg)

Now goto TestLists2.c.lis and set a breakpoint e.g. beneath _main:
![Bildschirmfoto 2020-05-31 um 23 37 19](https://user-images.githubusercontent.com/3081973/83363226-ff7d1c80-a397-11ea-98a4-81706e734966.jpg)
It should work.

Press start and you should break at _main.

**Comment by Blackbelt61** [comment]
Well, this is exactly what I am doing.
I start the debugging session and land in the compiler preamble:

![Screen Shot 05-31-20 at 11 50 PM](https://user-images.githubusercontent.com/65045422/83363519-571c8780-a39a-11ea-90b4-81a7d488aa8a.PNG)

Then I open the TestLists2.c.lis file and try to set a breakpoint, but it is always invalid:

![Screen Shot 05-31-20 at 11 51 PM](https://user-images.githubusercontent.com/65045422/83363558-9ba82300-a39a-11ea-9590-02099a2596d2.PNG)

TestLists2.lis file is completely different and doesn't contain the _main entrypoint, in fact I don't use it.

It is really strange that the same setup that doesn't work for me works like a charm on your computer.

I am using a portable version of VSC 1.45.0, but I don't think that it can be the problem.

**Comment by maziac** [comment]
Strange.
The only thing I changed were the path slashes because I‘m on macos.
Could you check if the paths are correct.
You could also try changing all \\ to / in launch.json. I think vscode can deal with it.

**Comment by Blackbelt61** [comment]
So, I have finally found a way.
I have tried to change the path slashes as you suggested, but it didn't work.
I have then removed some ${workspaceRoot} from tasks.json and launch.json and now my breakpoints are verified :-)

Here are the new working task.json and launch.json

[vscode.zip](https://github.com/maziac/DeZog/files/4710745/vscode.zip)

I don't know why I had to remove those ${workspaceRoot} to get the debugger work, but it works and that's enough for me ;-)

Thank you for your help!

Should you need mine for some test, please ask and I will be happy to help.

**Comment by maziac** [comment]
Good to know that it works now.
As it worked for me it seems that these are different in windows and mac.

Have fun with DeZog.

**Comment by Blackbelt61** [comment]
Hi @maziac ,

I have updated all the z88dk and vscode/dezog environment after some (long) time but it seems that the long gone problem with the c.lis files from z88dk has raised again.

In fact I am receiving this error

'dezogif v2.1.0' initialized.
Unverified breakpoint: {"verified":false,"line":7,"column":0,"source":{"name":"Test.c","path":"d:/TEST_C/Test.c","sourceReference":0}}
  Additional info: Address not found for d:/TEST_C/Test.c

on a very simple C program that you can dindi in the attached zip file

[TEST_C.zip](https://github.com/maziac/DeZog/files/10251943/TEST_C.zip)

I am using the latest z88dk version (2.2) 

Thank you in advance for any help you could give here.

**Comment by maziac** [comment]
The TEST_C.zip does not contain the .vscode folder. Could you please add.

**Comment by Blackbelt61** [comment]
Sorry about it.

Here is the TEST_C.zip file again, with the .vscode folder.

[TEST_C.zip](https://github.com/maziac/DeZog/files/10252310/TEST_C.zip)

**Comment by maziac** [comment]
Can I use your code (TEST_C.zip) as a test case inside DeZog?
It is just a small code snippet but can you put it under MIT license.

**Comment by Blackbelt61** [comment]
Of course! You can use the TEST_C.zip for whatever you want!
I am not sure I can add any MIT license on the Test.c file: it is just an "Hello World" example...

**Comment by maziac** [comment]
I think your statement above in the comments is enough.
Thanks.

**Comment by maziac** [comment]
I managed to get it working.

There is a zsim config in your launch.json that is still z88dk (version 1) but I guess you know that.

In the other config ("ZXNEXT") the "path" is set to "Test.lis" it should point to "Test.c.lis".
Further, he "srcDirs" is set to [""] this will turn the parsing into the source file mode.
I.e. it searches for the asm files that the z88dk c-compiler has created e.g "C:/Users/black/AppData/Local/Temp/zcc000053A8FE882.asm".
The files are not there but anyhow we should use the list file mode, i.e. the "srcDirs" need to be changed to "[]" (no string inside).

That's for the configuration.

But still it will not work.

You used a z88dk compiler that produces an output for the addresses that uses 6 digits.
The newest z88dk sources have corrected this, so dezog was only expecting 4 digits.
Anyhow I now included this "dialect" in dezog as well. I.e. dezog can now deal with z88dk v2 output that uses either 4 digits or 6 digits for the addresses.

Pleases make these changes to your config, use the attached vsix and tell me if it works.

Here is the config part that I used:
~~~json


        {
            "type": "dezog",
            "request": "launch",
            "name": "my zsim",
            "remoteType": "zsim",
            "zsim": {
               "memoryModel": "ZX48K"
            },
            "z88dkv2": [
                {
                    "path": "Test.c.lis",
                    "mapFile": "Test.map",
                    "srcDirs": []
                }
            ],
            "startAutomatically": false,
            "history": {
                "reverseDebugInstructionCount": 10000,
                "codeCoverageEnabled": true
            },
            "rootFolder": "${workspaceFolder}",
            //"topOfStack": "stack_top",
            "load": "Test.sna",
            "smallValuesMaximum": 513,
            "tmpDir": ".tmp"
        },
~~~

I used zsim for convenience, you can as well use the "zxnext".
[dezog-3.1.2-rc2.vsix.zip](https://github.com/maziac/DeZog/files/10254680/dezog-3.1.2-rc2.vsix.zip)

**Comment by Blackbelt61** [comment]
Unfortunately still doesn't work.

I have installed your lates vsix and just to be sure I now have only your suggested configuration in the launch.json, but still getting the same error.

![image](https://user-images.githubusercontent.com/65045422/208331807-17553fe6-5948-4453-a42d-41249b5c95dc.png)

Here is a new zip with the latest compiled files.

[Uploading TEST_C.zip…]()

I am using Windows 10

**Comment by maziac** [comment]
That should be OK.
You need to step to
call _main
and step into.
Then it will change to Test.c.lis and you can set a Breakpoint.

**Comment by Blackbelt61** [comment]
Oh yes! It works :)
I will try with some more complicated project: more files, libraries, etc.

Thanks a lot by now!
