### ISSUE TITLE
Duplicate memory window

### ISSUE THREAD

**Issue by infromthecold** [maziac/DeZog#33]
When i restart the debugging session DeLog creates a new memory window "Memory Dump @HL @DE......" producing two or more versions of the same window.

1 Enter a debugging session
2 Step into your code
3 Click restart the debugging session 

Repeat many times,creates and you get many windows

**Expected behavior**
I would expect it to either close or reuse the same window

All version of DeZog
Windows 10
CSpect and SpecNext Hardware

launch.json
{
        // Use IntelliSense to learn about possible attributes. //cspect
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": 
        [
            {                 
		//"preLaunchTask": "prelaunch",               
		"type": "dezog",
		"request": "launch",
		"name": "Z80 Debugger",               
		"remoteType": "zxnext",//"cspect",// "zxnext","zsim",
		"zsim": 
		{
			"Z80N": true,
			"loadZxRom": true,
			"zxKeyboard": true,
			"visualMemory": "true",
			"ulaScreen": true,
			"memoryPagingControl": true,
			"tbblueMemoryManagementSlots": true,
			"cpuLoadInterruptRange": 1,
			"vsyncInterrupt": true
		},
		"zrcp": 
		{
			"hostname": "localhost",
			"port": 11000
		},
		"cspect": 
		{
			"hostname": "localhost",
			"port": 11000
		},
		"zxnext": 
		{			
			"baudrate": 921600, //115200,
			"port": 12000,	//"/dev/tty.usbserial"
		},		
		//          "topOfStack": "Stack_Top",
		"rootFolder": "${fileDirname}",
		"listFiles": 
		[
			{				
				"useFiles": true,		  
				"asm": "sjasmplus", 
				"path": "${relativeFileDirname}/main.list",
				"mainFile": "${relativeFileDirname}/main.asm",	
				"cwd": "${workspaceFolder}",
			}
		],
		"disassemblerArgs": 
		{
			"esxdosRst": true
		},
		"load": "f:\\SpectrumNext\\Projects\\Komodo\\Build\\main.nex",
		"skipInterrupt": false,
		"startAutomatically": false,	
		"commandsAfterLaunch": [
			"-LOGPOINT enable",
		]
            }
        ]
    }

**Comment by maziac** [comment]
Please try this:
https://github.com/maziac/DeZog/releases/tag/v1.4.11

**Comment by infromthecold** [comment]
That works a treat!

Great stuff!
