### ISSUE TITLE
DZRP versions do not match

### ISSUE THREAD

**Issue by Gorlock** [maziac/DeZog#36]
Hi There,

I keep getting this error:

DZRP versions do not match. Required version is 1.6. But this remote (Unknown) supports only version 1.0. Try updating the DeZog (CSpect) Plugin (https://github.com/maziac/DeZogPlugin/releases).

Although the latest version available is 1.5.4.

Can you help me please?

Thank you!
Regards,
Gorlock

**Comment by maziac** [comment]
Seems that you are for some reason not using the DeZog Plugin 1.5.0.
I just tested the DeZog version 1.5.4 with DeZog Plugin version 1.5.0 from GitHub and it is working for me.

If you start CSpect from command line you should see a line
~~~
Dezog Plugin: v1.5.0.23723 started.
~~~

Make sure that the DeZogPlugin.dll is in the same directory as the Cspect executable is.

**Comment by Gorlock** [comment]
I just tried version 1.5 again, and it is working now.  Sorry, I might have done some changes on the launch.json in between versions, and in the end got stuck with 1.5.4 version without trying the new launch with 1.5.

![image](https://user-images.githubusercontent.com/2013880/97371715-23715b00-186f-11eb-896a-f43822c531f0.png)

Thank you so much!
Regards,
Gorlock

**Comment by maziac** [comment]
Fine that it is working now.
However from the picture you submitted I can see that you  are not doing source code debugging yet.
I.e. no sources are found and so the disassembler kicks in as fallback (disarms.asm).

If you want to do source level debugging (i.e. stepping through the main.asm file) please let me know.
