### ISSUE TITLE
Can't see values of memory view in light theme

### ISSUE THREAD

**Issue by remy** [maziac/DeZog#41]
**Describe the bug**

Can't see values of memory view in light theme. Specifically the values are made bold and white - see screenshot (further in the issue).

**To Reproduce**

1. Select a "light" theme i.e. "Light+ (default light)"
2. Memory view from the console: `-mv $c000 100`
3. The 100 highlighted bytes are white on a light background.

**Expected behavior**

Bold on the default font colour is used rather than white (or white hard coded).

**Screenshots**

<img width="905" alt="Screenshot 2021-01-04 at 18 00 19" src="https://user-images.githubusercontent.com/13700/103564666-d507ba80-4eb6-11eb-89cb-e14a87b0a804.png">

**Version etc. (please complete the following information):**
 - DeZog SW Version: 2.0.3
 - OS: macOS - Big Sur (do not recommend!)
 - Remote: zsim

**Comment by maziac** [comment]
Thanks. Will correct that in the next release.

**Comment by maziac** [comment]
You can test if it works in the latest pre-release:
https://github.com/maziac/DeZog/releases/tag/v2.1.0
(Don't forget to update the CSpect DeZog plugin as well).

**Comment by remy** [comment]
<img width="670" alt="Screenshot 2021-01-05 at 17 07 23" src="https://user-images.githubusercontent.com/13700/103676010-7dca1e80-4f78-11eb-8371-34f656f4a832.png">

Perfect - thank you 👍 

I've spotted a regression in another point - do you want me raise it separately or on the back of this? (it's that `-mv $c100 $ff` doesn't work now, I have to type `-mv 0xc100 0xff` instead)…

**Comment by remy** [comment]
Ah, that regression seems to apply more broadly too - the conditional breakpoints don't support `$ff` syntax either:

<img width="755" alt="Screenshot 2021-01-05 at 17 08 44" src="https://user-images.githubusercontent.com/13700/103676162-ace09000-4f78-11eb-80b5-b0dcc6c1fcd4.png">

**Comment by maziac** [comment]
Yes, please enter another error.
Did this work in the past ? I really can't remember?

**Comment by remy** [comment]
It did - and no problem, filing new issue 👍

**Comment by maziac** [comment]
Fixed in 2.1.0.
