### ISSUE TITLE
Regression: can't use $00 syntax on breakpoints or console

### ISSUE THREAD

**Issue by remy** [maziac/DeZog#43]
**Describe the bug**

Using `$` as a hex prefix value does not work, i.e. I can't refer to 255 as `$ff` anymore.

**To Reproduce**
1. Start debugging
2. In the debug console type: `-mv $c000 $ff`
3. See error (screenshot below)

**Expected behavior**

This was/is working in 2.0.3

**Screenshots**

![](https://user-images.githubusercontent.com/13700/103676162-ace09000-4f78-11eb-80b5-b0dcc6c1fcd4.png)

<img width="531" alt="Screenshot 2021-01-05 at 17 42 27" src="https://user-images.githubusercontent.com/13700/103679925-62addd80-4f7d-11eb-85a6-f895bd9fb00e.png">

**Version etc. (please complete the following information):**
 - DeZog SW Version: 2.1.0 (pre-release)
 - OS: macOS Big Sur
 - Remote: zsim 

---

Side note, I'm looking through the diff on the `develop` branch to see if I can see where the change is but thus far can't see it. I wonder if it's somewhere in `src/misc/utility.ts` file as the error in the debug console refers to a eval fail and I suspect [this line](https://github.com/maziac/DeZog/blob/develop/src/misc/utility.ts#L266) which suggests the `replaceVarsWithValues` has a regression in it - but again, I can't see this in the diff…

**Comment by remy** [comment]
Not tested it yet, but it could be [this commit](https://github.com/maziac/DeZog/commit/4b3e535f1ff9ef2655558a844f6c52b6af72e0c7#diff-ead2dc8a47853d0f76d5636f59b3fff570ef93fa13e9b2f02ecdacf230ec2a56)

**Comment by maziac** [comment]
Yes, that's it. The regex was broken. I corrected it on 'develop' branch.

**Comment by remy** [comment]
Theory:

This is the difference in the utility.ts commit that [tweaked the regexp](https://github.com/maziac/DeZog/commit/4b3e535f1ff9ef2655558a844f6c52b6af72e0c7#diff-ead2dc8a47853d0f76d5636f59b3fff570ef93fa13e9b2f02ecdacf230ec2a56):

<img width="884" alt="Screenshot 2021-01-05 at 18 06 05" src="https://user-images.githubusercontent.com/13700/103682420-c554a880-4f80-11eb-8d47-1bcb46d96220.png">

So previously when `$ff` went in, it came out the same, but the new regexp returns `ff`.

That value then goes into `Utility.parseValue` ([here](https://github.com/maziac/DeZog/blob/master/src/misc/utility.ts#L96-L109)) and the value is no longer prefixed with `$` and it doesn't match a label, so the value is returned as is - which eventually throws an error further down the chain.

**Comment by maziac** [comment]
Please try the new v2.1.3:
https://github.com/maziac/DeZog/releases/tag/v2.1.3

**Comment by remy** [comment]
Works perfectly - thank you 🙏
