### ISSUE TITLE
Watch doesn't support byte group above 2

### ISSUE THREAD

**Issue by remy** [maziac/DeZog#56]
**Describe the bug**

If you try to watch a value grouped by 4 bytes (for 32bit) the result is wrong/corrupted.

**To Reproduce**

Add a watch for an address with `4` as the argument:

<img width="359" alt="Screenshot 2021-04-25 at 10 07 46" src="https://user-images.githubusercontent.com/13700/115991972-0c63b980-a5c3-11eb-9934-a7d0d3948f6d.png">

**Expected behavior**

32bit groupings to be parsed. I would also expect 64bit - but I'm not sure what grouping by 3 bytes would do (or just a 24bit value?).

**Version etc. (please complete the following information):**
 - DeZog SW Version: 2.2.3
 - OS: macOS Big Sur
 - Remote: n/a

**Comment by maziac** [comment]
Could you please try this version v2.2.4:
https://github.com/maziac/DeZog/releases/tag/v2.2.4

I have done some re-factoring. If you encounter any other problems please let me know.

**Comment by remy** [comment]
Looks good to me 👍
