### ISSUE TITLE
ini instruction

### ISSUE THREAD

**Issue by denisiorus** [maziac/DeZog#89]
can't read zx-spectrum emulated keyboard with **ini** instruction. **in a,(c)** works as expected.

**Comment by maziac** [comment]
Could you maybe share your project (launch.json) and code.
Even better your whole zipped project.

**Comment by denisiorus** [comment]
[inisamp.zip](https://github.com/maziac/DeZog/files/8500159/inisamp.zip)

polls keys: 0,9,8,7,6,N,Y,Q 
pay attention to lines: 40 (main.asm), 200 (keys.asm)

**Comment by maziac** [comment]
Seems to work for me. I tested here with the Z-key.
![keyb](https://user-images.githubusercontent.com/3081973/163683825-592ffa24-9d11-43dd-8b08-e44b0d530dc6.gif)
For e.g. '9' it works also the same.

**Comment by denisiorus** [comment]
Change **IF 1** to **IF 0** at line 201 (keys.asm). It works because INI instruction is replaced by piece of code: 
in a,(c) 
ld (hl),a
inc l

**Comment by maziac** [comment]
Ah, I see.
And you are right, the INI instruction is not working.
I fixed it now: It documented B to early.
Please try the new vsix here https://github.com/maziac/DeZog/releases/tag/v2.6.3-rc1
and let me know if it is working.

**Comment by denisiorus** [comment]
Yes, now **ini** works well. But I decided to check **ind** and it doesn't work. I guess it decrements B too early too :) Maybe you should check all of similar instructions like: INIR, INDR, OUTI, etc...

**Comment by maziac** [comment]
Shit.
Please try the rc2 here: https://github.com/maziac/DeZog/releases/edit/v2.6.3-rc1
OUT was correct already beforehand.
The R(epeat) instructions just call the single instruction in a loop. So that should be fine as well.
