### ISSUE TITLE
watch block of memory  show same memory position multiple times

### ISSUE THREAD

**Issue by cardosojoao** [maziac/DeZog#94]
**Describe the bug**
have a watch configure like batch render_quere,2,400 the goal is to see a list of 400 elements each with 2 bytes

**To Reproduce**

during the update of memory I notice that the second block 100..199 position 100 was showing the the same as first block  0..99 position 50.

**Expected behavior**
show the correct memory position

**Screenshots**
![image](https://user-images.githubusercontent.com/1773533/183301647-e35495b9-d95f-4257-a16c-23590aa97a06.png)

**Version etc. (please complete the following information):**
 - 2.7.1
 - OS: windows 
 - Remote: cspect  2.16.5

**Comment by maziac** [comment]
Thanks for reporting.
Please try the fix in attached vsix here:
https://github.com/maziac/DeZog/releases/tag/v2.7.2

**Comment by maziac** [comment]
Is it working for you?

**Comment by maziac** [comment]
Released 2.7.2.

**Comment by maziac** [comment]
If you like DeZog please consider writing a review:
https://marketplace.visualstudio.com/items?itemName=maziac.dezog&ssr=false#review-details
