### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by infromthecold** [maziac/DeZog#98]
Hi
Maziac, I hope you are well, I have a question, is the functionality for the watches able to do complex reads and calculations?

![watch](https://user-images.githubusercontent.com/8275224/193602450-7950daad-0b3c-4b0b-a9b2-d978a6053e2e.png)

The image above demonstrates that the complex calculation evaluates to a wrong value which I am assuming is the error value as its being substituted for both the x and y calculations

((ix+object.fixedYPos)-(iy+object.fixedYPos))>>4 should be $0002 and not $D342
((ix+object.fixedXPos)-(iy+object.fixedXPos))>>4 should be $00bb and not $D342

As you can see in this image the values are incorrect even without the bit shifts

![nobits](https://user-images.githubusercontent.com/8275224/193602533-abb22fcd-5531-4e53-ae7c-1208033666c7.png)

Patricia

**Comment by infromthecold** [comment]
Hey Maziac       
           I don't think you need the snippet as this is a breakpoint before the functionality, and you can see the raw values for   ix+object.fixedYPos, iy+object.fixedYPos, ix+object.fixedXPos and iy+object.fixedXPos in the images which are correct,
           
in the image below       

ix+object.fixedYPos is $0AF0
iy+object.fixedYPos is $0AA0
           
$0AF0-$0AA0 should be $0050 for the ix+object.fixedYPos-iy+object.fixedYPos calculation

ix+object.fixedXPos is $17D0
iy+object.fixedXPos is $0C00

and $17D0-$0C00 should be $0BD0 for the ix+object.fixedXPos-iy+object.fixedXPos calculation
           
as you can see its still producing a wrong value without the inner parentheses.

![noInner](https://user-images.githubusercontent.com/8275224/193741869-edce32e4-d367-4cd9-b905-7d8a354e7070.png)

And with no parentheses

![noBracket](https://user-images.githubusercontent.com/8275224/193742009-36293001-7410-4321-8322-092d08b88211.png)

Patricia

**Comment by maziac** [comment]
E.g.
ix+object.fixedYPos is $0AF0
i.e. it is the contents of the address pointed to by ix+object.fixedYPos

When you do 
ix+object.fixedYPos - iy+object.fixedYPos
you do **pointer arithmetics**.

Lets assume ix+object.fixedYPos is pointing to 0xB000 and
iy+object.fixedYPos is pointing to 0xA000 then the result is 0x1000.
The watch expression will then return the value pointed to by 0x1000.

I guess you are trying to achieve to get the distance, i.e. the difference of the **contents**  of ix+object.fixedYPos
subtracted by the **contents** of iy+object.fixedYPos.

I guess that cannot be achieved in the watches.

**Comment by maziac** [comment]
BTW, if you like you can try a preview of DeZog 3.0:
https://github.com/maziac/DeZog/releases/tag/v3.0.0-rc1

**Comment by infromthecold** [comment]
Maziac
        Will do, changing web servers at the moment, so I'm pretty busy :)

Many thanks

**Comment by maziac** [comment]
Is it OK to close this?

**Comment by infromthecold** [comment]
Hi  Maziac
            Sorry yes , close it.

Many thanks
Trish
